[package]
name = "rayst"
version = "0.1.0"
edition = "2021"
rust-version = "1.87.0"

[dependencies]
image = "0.25.6"
nalgebra = { version = "0.33.2", features = ["rand"] }
rand = "0.8.5"
rand_distr = "0.4.3"
